name: push-new-branch
on: push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: yarn install
  test:
    needs: install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npx prettier --check .
      - run: yarn run eslint .
      - run: yarn run tsc
